- class: RectangularCoil
  dimensions:
    axDash: 1
    azDash: 1
  mfs_version: 1.2.0
  name: ''
  origin:
  - 0
  - 0
  - 0
  phi: 0.0
  strength: 1
  theta: 0.0
- class: CoilPair
  dimensions:
    axDash: 0
    axial layers: 10
    axial spacing: 0.001
    azDash: 0
    configuration: hh
    full spacing: 1
    radial layers: 10
    radial spacing: 0.001
    radius: 1
    shape: circ
    spatially distributed: true
  mfs_version: 1.2.0
  name: ''
  origin:
  - 0
  - 0
  - 0
  phi: 0.0
  strength: 1
  theta: 0.0
